sudo: required
services:
  - docker

before_install:
  - docker build -t atambe/react-webapp01 -f Dockerfile.dev .

language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - docker run -e CI=true atambe/react-webapp01 npm run test -- --coverage
  - npm run build
